#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor VGA-1 -d I II III IV V
bspc monitor DP-1 -d  VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           10 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#484848"
bspc config focused_border_color "#008000"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

feh --bg-fill --randomize ~/imgs/wallpaper/* &
~/.config/polybar/./launch.sh --shapes &
systemctl --user enable --now ulauncher.service &
# systemctl start iwd &
# iwctl --passphrase rr29261522 station wlan0 connect Tao5 &
# iwctl --passphrase 0146628794 station wlan0 connect "Fibertel WiFi033 5.8Ghz" &
# iwctl --passphrase 4464794 station wlan0 connect "Speedy-juan123"
# iwctl --passphrase 28364429 station wlan0 connect "sanmartin1"
sudo dhcpcd -S ip_address=172.27.7.53 -S routers=172.27.1.70 -S domain_name_servers=200.49.130.44,200.42.4.204 eno1 &
thunderbird &
pidgin &
picom -f &
