#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor HDMI-1 -d  VI VII VIII IX 
bspc monitor eDP-1 -d I II III IV V

bspc config border_width         5 
bspc config window_gap           5
bspc config split_ratio          0.84
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#484848"
bspc config focused_border_color "#008000"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

feh --bg-fill --randomize ~/imgs/wallpaper/* &
~/.config/polybar/./launch.sh --shapes &
xrandr --output eDP-1 --brightness 1.0  &
sudo /home/ivanse/.config/bspwm/setb.sh 1.0 &
systemctl --user enable --now ulauncher.service &
systemctl start iwd &

# iwctl --passphrase rr29261522 station wlan0 connect Tao5 &
# iwctl --passphrase 0146628794 station wlan0 connect "Fibertel WiFi033 5.8Ghz" &
# iwctl --passphrase 2994434704 station wlan0 connect "Speedy-juan123"
iwctl --passphrase 28364429 station wlan0 connect "sanmartin1"
kitty &
picom -f &
